### ISSUE TITLE
SuperDuperTrans.gff has wrong entries for special cases

### ISSUE THREAD

**Issue by nadiadavidson** [Quarkins/SuperTranscript#10]
I found a few odd entries in the chicken SuperDuperTrans.gff for the genes AKAP2 and FAM188B. Blocks are annotated beond the length of the super transcript. Both these gene have another gene that includes there name (PALM2-AKAP2 and INMT-FAM188B) and I think the annotation of these is getting confused. Some output from a command I was running that ran into the issue is pasted below.

Feature (AKAP2:4374-5634) beyond the length of AKAP2 size (3007 bp).  Skipping.
Feature (AKAP2:5637-7198) beyond the length of AKAP2 size (3007 bp).  Skipping.
Feature (FAM188B:2849-3179) beyond the length of FAM188B size (753 bp).  Skipping.
Feature (FAM188B:3179-3409) beyond the length of FAM188B size (753 bp).  Skipping.
Feature (FAM188B:2849-3179) beyond the length of FAM188B size (753 bp).  Skipping.
Feature (FAM188B:3179-3237) beyond the length of FAM188B size (753 bp).  Skipping.
Feature (FAM188B:3238-3282) beyond the length of FAM188B size (753 bp).  Skipping.

**Comment by Quarkins** [comment]
Fixed. Bug due to not looking for explicit gene name
